services:
  db_update_ec2:
    container_name: db_update_ec2
    build:
      context: .
      dockerfile: db.Dockerfile
    image: db_update_test:version_3.9.3
    env_file:
      - /home/shashank_daaslabs/Software/ec2_common.env
    environment:
      - POSTGRES_SCHEMA=ec2_prod
      - EMAIL_ENV=Production
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/ec2_common.env:/mnt/env/ec2_common.env

