services:
  db_update_local:
    container_name: db_update_local
    build:
      context: .
      dockerfile: db.Dockerfile
    image: db_update_local:version_3.9.3
    env_file:
      - .env
    environment:
      - POSTGRES_SCHEMA=loc_new
      - EMAIL_ENV=localhost
    volumes:
      - /home/sraj/Documents/OD_DB_Files/:/mnt/data/
      - /home/sraj/Documents/GitHub/ETL_Utilities/.env:/mnt/env/.env
